name: ansible-lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: ansible-lint
    steps:
      - uses: actions/checkout@v1
      - name: Lint playbook
        uses: ansible-community/ansible-lint-action@main
